version: 2.0
jobs:
  build:
    machine:
      enabled: true

    steps:
      - checkout
      - run: 
          name: Build Image
          command: |
            set -x
            SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            docker build -f multistage.Dockerfile -t <dockerhub-user>/flask-docker-demo-small:$SHORT_GIT_HASH .
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push <dockerhub-user>/flask-docker-demo-small:$SHORT_GIT_HASH

workflows:
  version: 2
  build:
    jobs:
      - build
